steps:
  # Build and tag the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west2-docker.pkg.dev/quantum-monitor-402021/esisa-docker-repo/esisa-monitor:v0', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west2-docker.pkg.dev/quantum-monitor-402021/esisa-docker-repo/esisa-monitor:v0']

  # Run docker-compose
  - name: 'docker/compose'
    args: ['up', '-d']

#images:
#  - 'us-west2-docker.pkg.dev/quantum-monitor-402021/esisa-docker-repo/esisa-monitor:v0'